import './globals.scss';
import { Quicksand } from 'next/font/google';
import Header from './components/Header';
import 'react-toastify/dist/ReactToastify.css';

const quickSand = Quicksand({ subsets: ['vietnamese'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={quickSand.className}>
        <Header />
        <div className="pt-24 h-screen">{children}</div>
      </body>
    </html>
  );
}
